crawler/articles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^all$', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>\d.*)$', views.article_text, name='article_text'),
    url(r'^tag/(?P<tag_name>\w.*)$',views.tag_roundup, name='tag_roundup')
]

crawler/crawler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^articles/', include('articles.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('articles.urls')),
    url(r'^feeds/', include('articles.urls')),
]

crawler/articles/models.py
from django.db import models
from django.utils import timezone
from articles.scraper import *
import logging


# Create your models here.

def get_default_feed():
    '''

    Dummy method to return our bogus feed... 
    probably can do better than just returning 3.

    '''
    return 3#    return Feed.objects.get(pk=3)



class Feed(models.Model):
    last_ripped = models.DateTimeField(null=True)
    feed_url = models.TextField(max_length=500)
    log = logging.getLogger(__name__)

    def __str__(self):
        return self.feed_url

    def get_latest_articles(self):
        self.log.debug("Getting latest articles for feed {}".format(self.feed_url))
        
        """
        we need to somehow intuit the right scraper...
        ... I'm so sorry
        """
        if "nytimes.com" in self.feed_url:
            scraper = NYTScraper(self.feed_url)
        elif "tsn.ca" in self.feed_url:
            scraper = TSNScraper(self.feed_url)
        elif "sportsnet.ca" in self.feed_url:
            print("initializing sportsnet scraper...")
            scraper = SportsnetScraper(self.feed_url)

        scraper.scrape_all()
        for raw_article in scraper.articles:
            # print("Raw: {}".format(raw_article))
            a = Article()
            a.article_url = raw_article["article_url"]
            a.article_title = raw_article["article_title"]
            if not raw_article["pub_date"]:
                a.pub_date = timezone.now()
            else:
                a.pub_date = raw_article["pub_date"]
            a.parent_feed = self
            if len(Article.objects.all().filter(article_title=a.article_title)) == 0:
                print("[SCRAPING] '{}'".format(a.article_title))
                a.article_text = scraper.get_article_text(a.article_url)
                a.save()
            else:
                print("[CACHED] '{}'".format(a.article_title))

class Article(models.Model):
    pub_date = models.DateTimeField(default=timezone.now)
    article_url = models.TextField(max_length=500)
    article_title = models.TextField(max_length=200)
    article_text = models.TextField(null=True)
    parent_feed = models.ForeignKey("Feed", default=get_default_feed)
    tagged = models.BooleanField(default=False)

    def __str__(self):
        return self.article_title
    

class Tag(models.Model):
    tag_name = models.TextField(max_length=50)
    tagged_articles = models.ManyToManyField(Article)
    
    def __str__(self):
        return self.tag_name

crawler/articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from articles.models import Article,Tag


# Create your views here.


def index(request):
    article_list = Article.objects.order_by("pub_date").reverse()
    template = loader.get_template('articles/index.html')
    
    html = template.render(
        {
        'article_list':article_list,
        'all_tags':Tag.objects.all(),
        },request
    )
    return HttpResponse(html)

def tag_roundup(request,tag_name):
    article_list = None
    tag = Tag.objects.filter(tag_name=tag_name)
    if tag:
        article_list = tag[0].tagged_articles.order_by("pub_date").reverse()

    template = loader.get_template('articles/index.html')
    context = RequestContext(request, {
        'article_list':article_list,
        'all_tags':Tag.objects.all(),
        'tag':tag_name,
    })
    return HttpResponse(template.render(context))

def article_text(request, article_id):
    # Article.objects.get(pk=)
    a = Article.objects.get(pk=article_id)
    return HttpResponse(a.article_text)

crawler/articles/templates/articles/index.html
<html>
<head>
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<style>
		body {
			background-color:#339554;
			margin:0;
		}
		
		#menu {
			background-color:orange;
			height:150%;
			width:150px;
			position:fixed;
			overflow-y:scroll;
		}
		
		#menu > ul > li > a, #menu > ul > li > a.visited {
			text-decoration:none;
			color:#000;
		}
		
		#menu > ul > li {
			margin-top:3px;
			padding-left:10px;
			font-size:15pt;
			font-family: 'Source Sans Pro', sans-serif;
		}
		
		#menu > ul > li:hover {
			background-color:yellow;
		}
		
		#panel {
			display:flex;
			margin-left:150px;
		}

		
		#article_text {
			font-family:verdana,sans-serif;
			font-size:8pt;
			margin:10px;
			padding-top:10px;
		}
		#story_index {
			width:100%;
		}
	
		li.story {
			font-size:25pt;
			font-family: 'Raleway', sans-serif;
			border:1px solid #999999;
			margin:10px;
/*			padding:10px;*/
			padding: 2px 0px 0px 0px;
			padding-bottom:none;
			background-color:#fff;
			box-shadow: 2px 2px 3px #003300;
		    
		}
		ul {
			list-style-type:none;
			padding-left:0;
		}
		.tags > a, .tags > a.visited {
			font-size:12pt;
			margin:0;
			padding:3px;
			color:#fff;
			text-decoration:none;
			background-color:#000;
		}
		.tags {
			padding:0;
			margin:0;
			background-color:#aaa;
			display:flex;
		}
	</style>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	
	<script type="text/javascript">
		function get_text(article_id) {
			console.log("story " + article_id + " clicked")
			$.get( "/articles/" + article_id, function( response ) {
			    console.log( response ); // server response
				document.getElementById("article_text").innerText = response;
			});
		}
	</script>
	<link href='https://fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="menu">
	<ul>
		<li><a href="/articles/all">All</a></li>
		{% for tag in all_tags %}
		<li><a href="/articles/tag/{{tag.tag_name}}">{{tag.tag_name}}</a></li>
		{% endfor %}
	<ul>
</div>
<div id="panel">
<div id="story_index">
<ul>
{% for article in article_list %}
	<!--get_text({{article.pk}}) -->
    <li class="story" onclick="window.location.assign('{{article.article_url}}')">{{article.article_title}}
	<div class="tags">
		{% for tag in article.tag_set.all %}
			<a href="/articles/tag/{{tag.tag_name}}">#{{tag.tag_name}}</a>
		{% endfor %}
	</div>
	</li>
{% endfor %}

</ul>
</div><!--
<div id="middle">
	<ul>


	</ul>
</div>
<div id="article_text"></div>
</div>-->
</html>